### ISSUE TITLE
Rewrite for a 12-year-old

### ISSUE THREAD

**Issue by rwxrob** [rwxrob/books#3]

**Comment by TheShadowblast123** [comment]
My suggestions:
1. why-another-go-book.adoc should be moved into the faq, as a 12 year old is unlikely to know what go is and to know that there are plenty of go books. 

2. why-code.adoc and why-go.adoc feel more like things addressing parents and teachers. A 12 year old isn't going to be too aware of the market unless if they're in poverty and even then, if they're picking up this book, they likely know all points mentioned. I think having a "For parents, teachers, and guardians" section would be a better place and it'll tell younger readers to skip this section

3. get-computer.adoc features technical details on computer parts. I believe that having these details in will spark some curiosity and inspire some, but this is definitely a part where we need to say "please bring in your adult to assure this". Most parents won't know what these details mean either so this section will need to be broken down further so the tech illiterate can convey what they need to someone at Best buy or Walmart, because we know that some parent is going to those places for their computer. The operating system section is probably too technical. I suggest breaking it up into a simplified version, maybe saying what minimum budget is appropriate, then having a more technical side where operating systems and specs are mentioned.

4. In bring-your-phone.adoc, "bash command line and vim usage" the reader has not been introduced to either. You probably don't want to mention anything at all without explaining what they are. 

5. create-email-account.adoc, "Choosing the right email service
For most users, selecting a reliable and secure email provider is vital. While free services like Gmail are popular, privacy-focused options like ProtonMail offer additional benefits, including end-to-end encryption, a free VPN, and strong data protection." For cases like this, it might be better to say, if you know what this means [technical details], otherwise, just use something. "end-to-end endryption" and "VPN" fall into a nebulous category where readers may or may not know what they are, but we're probably never going to define them later in the book, and they're relatively unimportant if you're ignorant. For cases like this, reassuring the reader that it isn't super important to the rest of the reading that they understand what it means would be nice.

6. A rewrite of sections of create-github-account.adoc to make it not include technical jargon without some explanation.
 [Create a GitHub account](https://rwxrob.github.io/books/code-mage/#_create_a_github_account)
GitHub is one of the most powerful platforms for collaboration and code sharing... // removed version control here as it's not addressed until later

[Why create a GitHub account?](https://rwxrob.github.io/books/code-mage/#_why_create_a_github_account)
Version Control: GitHub is built on Git, a distributed version control system created by the inventor of Linux that helps you track changes in your code, collaborate with others, and maintain a history of your project. It is a system of keeping track of previous versions of your work. Think about it like being able to save your work, and still being able to go back and undo the whole last week's worth of work if you find that you made a mistake! //further explained version controlled here.

**Comment by TheShadowblast123** [comment]
7. start-taking-notes.adoc, it is now completely out of date with your beliefs as to note taking. I believe that further addressing this section beyond saying that maybe the reader doesn't need some of the markdown quite yet and if markdown is still included it should be sectioned off by level of need.

8. in learn-launcher.adoc, "Focus:Search and launch tools help you avoid distractions by providing a single interface for tasks." should be "Focus: Search and launch tools help you avoid distractions by providing a single interface for tasks."

I need to take a break for a bit

**Comment by TheShadowblast123** [comment]
Okay another consideration is the fact that there's very little use of the mage analogy for explanatory purposes. I'm going to suggest adding technical glossary that'll do something like the following:

peer review: Not all spells are developed alone, sometimes we need help. This is where peer review can help, as it is where we get a peer, friend, mentor, or any other fellow code mage and review our code together.

here's a possible start to a glossary that I wrote largely with the help of chatgpt:

== Glossary of Technical Terms

=== Programming Fundamentals (Magecraft Basics)
* **Variable**: A magical vessel used to store enchanted essences (data) for manipulation during spellcasting (execution).
* **Logic**: The spellbinding patterns and constructs (`if`, `else`, `for`, `while`) that shape the flow of magical energy (program behavior).
* **Function**: A codex of reusable incantations, designed to perform specific rituals. Functions modularize and simplify complex spellcasting sequences.
* **Data Structure**: Mystical frameworks for organizing and storing enchanted essences (data). Examples include the Bag of Holding (arrays), Spell Scrolls (lists), and Arcane Tomes (hash maps).

=== Go-Specific Concepts (Rituals of Go-Mage)
* **`package main`**: Declares the heart of the spellbook, where rituals begin to take form.
* **`import`**: Channels external arcane energies (packages) into the spellbook for use.
* **`func main()`**: The ceremonial invocation where the mage’s rituals (program execution) commence.
* **`fmt.Println`**: An incantation from the `fmt` grimoire used to project words of power (output) onto the terminal void.
* **`go run`**: A command to energize (compile) and unleash (execute) the mage’s rituals immediately.
* **`go build`**: A command to forge a stable artifact (executable file) from the mage’s spellbook.
* **`go mod`**: A ritual for managing the mage’s arcane dependencies (modules).
* **`go install`**: A command to prepare and embed (build and install) the mage’s tools and libraries for future use.
* **`// comment`**: Glyphs of wisdom etched into the spellbook, ignored by the energy flow (execution).

=== Markdown Basics (Glyph Engraving)
* **Markdown**: A lightweight enchantment language for inscribing readable and structured glyphs (text).
* **Syntax**: The sacred runes and patterns that govern the form and function of glyphs.
* **GitHub Flavored Markdown (GFM)**: A variant of the glyph language with enhanced incantations, favored in the archives of GitHub.
* **AsciiDoc**: An advanced glyph language for crafting intricate tomes and scrolls, often used by elder scribes (technical writers).

=== Vim (The Mage’s Quill)
* **Vim**: A modal text grimoire celebrated for its swift and powerful glyph manipulation, wielded by adept Code Mages.
* **Modal Editing**: The mage’s method of switching between glyph navigation, inscription, and transformation modes.
* **Configuration**: The customization of the grimoire’s arcane properties and augmentation with plugins.
* **Unicode**: The universal codex of glyphs, enabling mages to inscribe spells in any language or symbol, even with emojis.


* **Alacritty**: A GPU-accelerated terminal emulator favored for its speed and customization. The Code Mage's wand for channeling spells (commands).
* **Bash**: The Code Mage's foundational chant—a command-line shell used to cast commands and manipulate the environment.
* **Brew**: A package manager for macOS, serving as a recipe book for installing and managing tools. 
* **cm**: The Code-Mage Assistant command, a spellbook for automating the setup of essential tools like bash, vim, and Alacritty.
* **Command**: A single invocation of a spell, performed in the terminal, forming the basic incantations of the Code Mage.
* **Git**: The core magic of version control, allowing the tracking, branching, and merging of work to ensure order and enable collaboration.
* **GitHub**: The great archive of repositories where Code Mages share their tomes (projects) and contribute to collective knowledge.
* **gh**: The enchanted artifact (GitHub CLI) for seamless interaction with GitHub repositories from the terminal.
* **Go**: A modern programming language celebrated for its simplicity and speed, used by Code Mages for crafting spells and enchantments.
* **Launcher**: A system tool for swiftly opening applications or files. The mage's shortcut to their wands and spellbooks.
* **Package Manager**: Tools like brew, winget, or apt that manage software installation. They are the mage's recipe scrolls for summoning tools.
* **Repository (Repo)**: A tome holding source code, documentation, and history of a project; the fundamental unit of organization for Code Mages.
* **Shell**: The chanting platform for invoking commands and casting spells to control the system.
* **Spellbook**: Scripts or configuration files holding collections of spells (commands) that automate tasks.
* **Spotlight**: macOS's built-in launcher for summoning apps or files. A shortcut to focus for the Code Mage.
* **Terminal**: The mage's staff, a powerful interface for casting commands and controlling the digital environment.
* **Vim**: A powerful text editor considered a primary tool for crafting and editing tomes. Favored by advanced Code Mages for its grimoire-like capabilities.
* **Wand**: Any specialized tool or utility used by a Code Mage to accomplish tasks efficiently, such as Alacritty or gh.
* **Winget**: A package manager for Windows, another recipe book for summoning software.
* **Workflow**: The sequence of actions and tools a Code Mage uses to achieve a goal. A refined workflow is the hallmark of an adept mage.

**Comment by rwxrob** [comment]
I absolutely love all this. Thank you! Will definitely add a glossary with a mage theme. A lot of the other reorg and prose rewrite was already planned but will be good to go through once I have a first draft with the rewrite.
